#!/bin/sh
ARG=$1
[ -z "$ARG" ] && echo "No argument to fetch from urban dictionary"
curl -L -s "http://www.urbandictionary.com/define.php?term=$ARG" | grep '<meta content' | grep "name='Description'" | cut -f2 -d"'" 

