#!/bin/sh

ARG=`echo $1|sed 's/ /%20/g'`

[ -z "$ARG" ] && echo "No argument to fetch from urban dictionary." && echo "Example: $ fud fud"

curl -L -s "http://www.urbandictionary.com/define.php?term=$ARG" | grep '<meta content' | grep "name='Description'" | \
	cut -f2 -d"=" | sed -e "s/name$//g"
